site_name: Cultura Transparente 
nav:
  - Home: index.md
  - Sprints: sprints.md
  - Organização do Projeto: 
      - Aquitetura: arquitetura.md
      - Storymap: storymap.md
  - Como Execultar o Projeto?: comoexecultar.md

theme: material 

